### ISSUE TITLE
/rpg reset NPE (v1.0.9)

### ISSUE THREAD

**Issue by foncused** [vvMv/rpgplus#60]
**Description of the bug**
Looks like an ACF NPE being thrown when attempting to reset a player's stats.
/rpg reset Jack_V
```
[ACF] Exception in command: rpg resetattributes Jack_V
[10:01:36] [Server thread/ERROR]: [ACF] java.lang.reflect.InvocationTargetException
[10:01:36] [Server thread/ERROR]: [ACF]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:01:36] [Server thread/ERROR]: [ACF]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:01:36] [Server thread/ERROR]: [ACF]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:01:36] [Server thread/ERROR]: [ACF]         at java.lang.reflect.Method.invoke(Method.java:498)
[10:01:36] [Server thread/ERROR]: [ACF]         at com.vmv.rpgplus.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[10:01:36] [Server thread/ERROR]: [ACF]         at com.vmv.rpgplus.acf.BaseCommand.executeCommand(BaseCommand.java:576)
[10:01:36] [Server thread/ERROR]: [ACF]         at com.vmv.rpgplus.acf.BaseCommand.execute(BaseCommand.java:512)
[10:01:36] [Server thread/ERROR]: [ACF]         at com.vmv.rpgplus.acf.RootCommand.execute(RootCommand.java:99)
[10:01:36] [Server thread/ERROR]: [ACF]         at com.vmv.rpgplus.acf.BukkitRootCommand.execute(BukkitRootCommand.java:79)
[10:01:36] [Server thread/ERROR]: [ACF]         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[10:01:36] [Server thread/ERROR]: [ACF]         at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723)
[10:01:36] [Server thread/ERROR]: [ACF]         at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1658)
[10:01:36] [Server thread/ERROR]: [ACF]         at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1498)
[10:01:36] [Server thread/ERROR]: [ACF]         at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[10:01:36] [Server thread/ERROR]: [ACF]         at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[10:01:36] [Server thread/ERROR]: [ACF]         at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[10:01:36] [Server thread/ERROR]: [ACF]         at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[10:01:36] [Server thread/ERROR]: [ACF]         at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[10:01:36] [Server thread/ERROR]: [ACF]         at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[10:01:36] [Server thread/ERROR]: [ACF]         at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[10:01:36] [Server thread/ERROR]: [ACF]         at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)
[10:01:36] [Server thread/ERROR]: [ACF]         at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)
[10:01:36] [Server thread/ERROR]: [ACF]         at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127)
[10:01:36] [Server thread/ERROR]: [ACF]         at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895)
[10:01:36] [Server thread/ERROR]: [ACF]         at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)
[10:01:36] [Server thread/ERROR]: [ACF]         at java.lang.Thread.run(Thread.java:748)
[10:01:36] [Server thread/ERROR]: [ACF] Caused by: java.lang.NullPointerException
[10:01:36] [Server thread/ERROR]: [ACF]         at com.vmv.rpgplus.command.Commands.resetAttribute(Commands.java:147)
[10:01:36] [Server thread/ERROR]: [ACF]         ... 26 more
```

**Comment by vvMv** [comment]
Looks like this is because the player is offline, will look into it thanks

**Comment by vvMv** [comment]
d3cfc35b23423619da1a2cef2204e2160dfa06d1
